### ISSUE TITLE
The YOG metaserver has refused connection because your Globulation 2 client is out of date.

### ISSUE THREAD

**Issue by seasquirt** [Globulation2/glob2#116]
Happens on latest version from the website on windows.

**Comment by stephanemagnenat** [comment]
This might be due to the recent recompilation of the server, see #113. @progval what do you think? I wonder whether it would solve that problem if we would revert to the previous version for the server until someone has time to release a new version binaries on the web site? I guess it would then break the master version. I'm not 100% sure which commit made that incompatible, probably 995801174219f8becda05cd32232a21e3f87249b.

**Comment by progval** [comment]
Restarted with:

```diff
diff --git a/src/YOGServer.cpp b/src/YOGServer.cpp
index ba8fea96..e7457e8e 100644
--- a/src/YOGServer.cpp
+++ b/src/YOGServer.cpp
@@ -181,7 +181,7 @@ YOGGamePolicy YOGServer::getGamePolicy() const
 
 YOGLoginState YOGServer::verifyLoginInformation(const std::string& username, const std::string& password, const std::string& ip, Uint16 version)
 {
-       if(version < NET_PROTOCOL_VERSION)
+       if(version < NET_PROTOCOL_VERSION - 1)
                return YOGClientVersionTooOld;
        if(loginPolicy == YOGAnonymousLogin)
                return YOGLoginSuccessful;
@@ -215,7 +215,7 @@ YOGLoginState YOGServer::verifyLoginInformation(const std::string& username, con
 
 YOGLoginState YOGServer::registerInformation(const std::string& username, const std::string& password, const std::string& ip, Uint16 version)
 {
-       if(version < NET_PROTOCOL_VERSION)
+       if(version < NET_PROTOCOL_VERSION - 1)
                return YOGClientVersionTooOld;
        if(loginPolicy == YOGAnonymousLogin)
                return YOGLoginSuccessful;
```

**Comment by stephanemagnenat** [comment]
Thank you @progval for the quick reaction! One question: why not using a fixed `NET_PROTOCOL_VERSION` here (in that case 27)?

I think that in the future we should decouple the meta-server version from the version for playing games over network. I created the issue #118 for that.
